### ISSUE TITLE
Existed version of cv32e40p pipeline graph

### ISSUE THREAD

**Issue by ahmdotm** [openhwgroup/cv32e40p#1030]
Is there a LaTeX for the core pipeline graph or the microarchitecture? or any other application or visual code?

**Comment by MikeOpenHWGroup** [comment]
Hi @ahmdotm, the only documentation supported for the CV32E40P core is written in ReStructured Text (rst) which can be found in the `docs` directory of this repository.  It is rendered to HTML by ReadTheDocs and published to https://docs.openhwgroup.org/projects/cv32e40p-user-manual/en/latest/
