### ISSUE TITLE
AXI interface

### ISSUE THREAD

**Issue by AlfredoRodrigues4** [openhwgroup/cv32e40p#1034]
For what I read, CV32E40P using OBI protocol, is that easy to integrate the AXI for the connection? Like a OBI-AXI bridge, or someone know if this is already developed in some way?

**Comment by MikeOpenHWGroup** [comment]
Hi @AlfredoRodrigues4, thanks for your interest in OpenHW and the CV32E40P.

> is that easy to integrate the AXI for the connection?

Probably not easy, but technically possible.  Having said that, it probably isn't worth the effort as the OpenHW CVE2 and CVE4 cores are all in-order Harvard machines. The [OBI](https://github.com/openhwgroup/obi/tree/main) more like the AHB in that is a single shared channel for both read and write operations. The CVE2 has a simple [OBI-to-AHB adaptor](https://github.com/openhwgroup/cve2/tree/main/examples/obi2ahb) which you could probably use with the CV32E40P core (or any of the other cores supporting OBI).  Please be aware that this adaptor has yet to be fully verified.

> Like a OBI-AXI bridge, or someone know if this is already developed in some way?

The PULP-Platform team has an [AXI to APB bridge](https://github.com/pulp-platform/axi2apb/tree/53e7b9f1b16e3f4d4aadc8fbf880d05879f54fe8), so you could look at that as well.

If this answers your question, please close this issue.  Thanks!
