### ISSUE TITLE
Address channel signal stability during non-granted REQ_O

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/cv32e40p#128]
Address channel signals (instr_addr_o, ....) are not kept stable during a non-granted instr_req_o. 

This prohibits efficient translation into popular protocols as e.g. AMBA AHB.

Please see attached pdf for details.

[RI5CY_Bus_Interface_2.pdf](https://github.com/pulp-platform/riscv/files/3541774/RI5CY_Bus_Interface_2.pdf)

**Comment by vogelpi** [comment]
FYI: we opened an Ibex issue lowrisc/ibex#296 to discuss the benefit and future of this behavior.
