### ISSUE TITLE
Violation - Accessing debug CSRs while not in debug mode

### ISSUE THREAD

**Issue by shetalani** [openhwgroup/cv32e40p#136]
Here is an issue found after applying OneSpin 360 DV-Verify RVV App on RI5CY:

**Description:** As the debug specification "RISC-V External Debug Support Version 0.13.1" states that: "The supported Core Debug Registers are only accessible from Debug Mode.", the core doesn't raise an illegal instruction exception for such a case.
**Example:** The instruction 32'h7B001073 (csrrw x0, dcsr, x0) is decoded at time point t##0 while the debug_mode signal is not set with no illegal instruction being flagged, as illegal_insn_dec is de-asserted. 

![issue_4](https://user-images.githubusercontent.com/54367010/63957121-19e03d80-ca88-11e9-9dc3-150061e314e4.PNG)

--------------------------------------------
Product: OneSpin 360 DV-Verify
App: RVV
Tool's version: 2019.2.1

**Comment by silabs-PaulZ** [comment]
This was fixed with pull request #326 
Attempting to access the core debug registers in non debug_mode will result in an illegal instruction.
