### ISSUE TITLE
ASIC synthesis target frequency

### ISSUE THREAD

**Issue by tangshibin** [openhwgroup/cv32e40p#207]
What's the target frequency should be set for RI5CY (pulpissimo-v2.0.1) under tsmc40lup;
I saw it can be synthesized up to 450MHz Under 40nm;(http://asic.ethz.ch/2017/Mr.Wolf.html)
But timing violation exists when it is synthesized for 200M under  40nm;
The timing violation is caused by a single-cycle 32x32 multiplier.
How can I improve the synthesis frequency?

**Comment by HazemFathy** [comment]
Have you reached a solution for the performance limited by the multiplier? @tangshibin

**Comment by barrydebruin** [comment]
I'm not sure if it helps, but i was able to synthesize it to 650MHz for 28nm RVT @ 0.9V, so it seems that there might be something wrong.

**Comment by HazemFathy** [comment]
And how you reached that performanc? is it about specific timing constraints applied ?

**Comment by barrydebruin** [comment]
No specific timing constraints. Im talking about the pulpino repo though.

**Comment by HazemFathy** [comment]
Aha, thanks.

**Comment by Silabs-ArjanB** [comment]
Hi @tangshibin It seems your question has been answered. Could you please close this issue?
