### ISSUE TITLE
remove deprecated parameters

### ISSUE THREAD

**Issue by davideschiavone** [openhwgroup/cv32e40p#217]
Remove and clean the code for:

```
  parameter FP_DIVSQRT          =  0,
  parameter SHARED_DSP_MULT     =  0,
  parameter SHARED_INT_MULT     =  0,
  parameter SHARED_INT_DIV      =  0,
  parameter SHARED_FP_DIVSQRT   =  0,

```
Make **parameter SHARED_FP**  always equal to 1

**Comment by davideschiavone** [comment]
According to @stmach , SHARED_FP is not a binary parameter.
The maintained version is SHARED_FP equal to 2.

Here the commit where the FPU is always outside the core. The SHARED* parameters have been removed.

2 pending questions:

What should be the value of SHARED_FP_DIVSQRT ? 
1 or 2?

Should the ALU still contain FPU instructions?

**Comment by Silabs-ArjanB** [comment]
Done
