### ISSUE TITLE
Path from data_rvalid_i to instr_req_o on 128b prefetcher

### ISSUE THREAD

**Issue by davideschiavone** [openhwgroup/cv32e40p#257]
There is a path in the prefetcher 128b wide that goes from the data_rvalid_i to the instr_req_o.

Such path limits signifantly the frequency in the PULP cluster.

**Comment by Silabs-ArjanB** [comment]
Sounds similar to (or same as) https://github.com/openhwgroup/cv32e40p/issues/126

**Comment by davideschiavone** [comment]
Hi @Silabs-ArjanB , not it's actually from **data**_valid to **instr**_req. So it's different.
Anyway, this is a specific PULP issue as the 128b won't be used by OHW for the moment

**Comment by Silabs-ArjanB** [comment]
Hi @davideschiavone Can you please close this issue as the 128b prefetcher has been removed?
