### ISSUE TITLE
VCD File for Power Analysis

### ISSUE THREAD

**Issue by HazemFathy** [openhwgroup/cv32e40p#291]
Hello , 

Can someone provide me with the vcd file generated from the core's testbench ? , to use it in power analysis in asic synthesis.

**Comment by davideschiavone** [comment]
Hello,

you should generate the VCD file by yourself using your benchmarks to calculate power.
We won't commit in the repository a VCD file that describe the activity of an application as 
"Hello world" as it is not representative of a typical workload in my opinion. Plus we don't want to push into repository generated files.

**Comment by HazemFathy** [comment]
I see , thanks davide.

**Comment by davideschiavone** [comment]
@HazemFathy , can we close this now? thanks
Davide

**Comment by HazemFathy** [comment]
Yes , thanks davide
