### ISSUE TITLE
Document retirement strategy per instruction group

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/cv32e40p#296]
To ease reviewing the cv32e40p RTL code it would be beneficial to clearly document the retirement policy for various instructions groups: Which instructions will retire in what pipeline stage and how is it guaranteed that instructions retire in program order.

The question came up in relationship with the handling of CSR instructions, see https://github.com/openhwgroup/cv32e40p/pull/262

**Comment by MikeOpenHWGroup** [comment]
Here here!  Thanks for opening this @Silabs-ArjanB.  The verification TG is working on the integration of an ISS, so we'll need this type of information soon.

**Comment by Silabs-ArjanB** [comment]
Not documented, but too late by now.
