### ISSUE TITLE
Cannot use PULP toolchain for interrupt_test

### ISSUE THREAD

**Issue by mp-17** [openhwgroup/cv32e40p#303]
The _interrupt_test_ does not work with the PULP toolchain, because: 

1) The PULP toolchain cannot handle arguments to **\_\_attribute__((interrupt(**_ARG_**)))**. A possible solution is not to give _ARG_.
2) The PULP toolchain cannot handle function calls inside interrupt functions (e.g. **software_irq_handler** calls **printf**).

The official riscv-toolchain works as expected, though.

**Comment by mp-17** [comment]
I cloned your repo with the fix and tried the interrupt_test with the PULP toolchain. 
Now it works! Thank you very much.

**Comment by davideschiavone** [comment]
https://github.com/openhwgroup/cv32e40p/pull/304
