### ISSUE TITLE
Delete old doc after double checking that all the features are part of the new one

### ISSUE THREAD

**Issue by davideschiavone** [openhwgroup/cv32e40p#312]
The new doc has a text format, much more readable and it has been provided by the kindness of @MikeOpenHWGroup 

https://github.com/openhwgroup/core-v-docs/pull/29

**Comment by MikeOpenHWGroup** [comment]
Not kindness.  We have already discussed my fee @davideschiavone.   I've updated the README in core-v-docs to point to the readthedocs rendering and published the availability of the new format on MatterMost.

**Comment by davideschiavone** [comment]
https://github.com/openhwgroup/cv32e40p/pull/316
