### ISSUE TITLE
Dead states in load/store unit

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/cv32e40p#317]
I am studying the current load/store unit in preparation for OBI related fixes. I see (using formal verification) that the WAIT_RVALID_EX_STALL and IDLE_EX_STALL can never be reached (in slightly out-of-date repos state, 8666456b147e4ed32590d10c920ea6c919761bc4).

Maybe they were reachable at some point (e.g. before we disallowed certain parameter settings as e.g. USE_PMP). Can somebody explain the (original) reason for these states (before I will proceed with removing them)?

Some other code does look a bit suspicious as well. To me the intention seems to be that lsu_ready_ex_o = 0 only if data_req_ex_i = 1 && data_gnt_i == 0 (this is the expression if CS = IDLE). However, in the WAIT_RVALID state this expression does not hold when data_rvalid_i = 0 

This does not hold when CS = WAIT_RVALID and data_rvalid_i = 0 in which case lsu_ready_ex_o will be set to 1 even if data_req_ex_i = 1 && data_gnt_i == 0. It does not lead to issues in the CV32E40P, but I think the lsu_ready_ex_o the WAIT_RVALID assignment of lsu_ready_ex_o should be fixed to properly indicate whether the EX stage is ready from a LSU perspective.

**Comment by davideschiavone** [comment]
Hello @Silabs-ArjanB ,

there are other people (you included btw) that also found this and reported it here:

https://github.com/openhwgroup/cv32e40p/issues/129
https://github.com/openhwgroup/cv32e40p/issues/80

We tried to reach with random instruction simulation that state back in 2017 and failed indeed.
We did not remove it as we did not investigate further with formal verification as well (or synthesis could work too as it should remove those states)

The designer left so we do not know the original reason . Probably it comes from the very first version based on OpenRISC. Maybe @gautschimi knows it?

I think we should remove them once we verify that Synthesis or Formal Tools confim that.

Best
Davide

**Comment by Silabs-ArjanB** [comment]
Hi @davideschiavone , I knew I reported something similar quite some time ago, didn't realize it was exactly the same, sorry for that. I also understand the reasoning for the lsu_ready_ex_o I asked about now (I will remove that from the original post). This ticket can be closed then.
