### ISSUE TITLE
Re-introduce Hardware Loop functionality

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/cv32e40p#406]
The Hardware Loop features (by choice) partially non-operational in CV32E40P, but will be made operational again. It was removed initially and agreed to be re-introduced again in a different manner (together with a Ariane style fetch FIFO implementation) after the bus interface related updates (which completed months ago).

Until this issue has been resolved Hardware Loops will be non-operational no matter the parameter settings.

**Comment by davideschiavone** [comment]
see PR #436

**Comment by davideschiavone** [comment]
Can we close this @Silabs-ArjanB ?
