### ISSUE TITLE
CPI too high for BLT and MUL?

### ISSUE THREAD

**Issue by barrydebruin** [openhwgroup/cv32e40p#43]
I have done some RTL simulations on the RISCV in combination with the Pulpino platform. To evaluate the Cycles Per Instruction, I counted the difference in cycle count between the current and next instructions.

Like this:

             Time                Cycles  PC       Instr    Mnemonic
             4840000             104     00000080 00c0006f jal              x0, 12             
             4920000             106     0000008c 30501073 csrrw            x0, x0, 0x305      
             4960000             107     00000090 00000093 addi             x1, x0, 0            x1=00000000

jal takes 106-104 = 2 cycles
csrrw takes 107-106 = 1 cycle 

and so on.

Now I came across a few remarkable observations:
- the blt instruction can take up to 63 cycles (<3 cycles on average though)!
- the mul instruction can also take up to 31 cycles (~1 cycle on average though)!

Is there any motivation why this can happen?

blt instruction trace snippet:
```
         Time                 Cycles PC       Instr    Mnemonic
         18177360000          454417 00001ddc 02a64533 div              x10, x12, x10       x10=00000b6a x12:00680000 x10:0000091c
         18178280000          454440 00001de0 00ab8bb3 add              x23, x23, x10       x23=00000b6a x23:00000000 x10:00000b6a
         **18178320000          454441 00001de4 f28b42e3 blt              x22, x8, -220       x22:00000008  x8:00000100**
         18180840000          454504 00001d08 00098693 addi             x13, x19, 0         x13=00100f58 x19:00100f58
         18180880000          454505 00001d0c 00000713 addi             x14, x0, 0          x14=00000000
         18180920000          454506 00001d10 00000c93 addi             x25, x0, 0          x25=00000000
```

mul instruction trace snippet:
```
         Time                 Cycles PC       Instr    Mnemonic
         18171080000          454260 00001db0 00f50533 add              x10, x10, x15       x10=02980000 x10:02340000 x15:00640000
         18171120000          454261 00001db4 03454533 div              x10, x10, x20       x10=00530000 x10:02340000 x20:00000008
         **18172360000          454292 00001db8 02e70733 mul              x14, x14, x14       x14=00000000 x14:00000000 x14:00000000**
         18173600000          454323 00001dbc 41275733 sra              x14, x14, x18       x14=00000000 x14:00000000 x18:00000004
         18173640000          454324 00001dc0 40e50533 sub              x10, x10, x14       x10=00530000 x10:00530000 x14:00000000
         18173680000          454325 00001dc4 0b5000ef jal              x1, 2228             x1=00001dc8
```

**Comment by davideschiavone** [comment]
Hello,

as you are using PULPino you should have 1cycle access to the instruction and data memory, 
so I can exclude that the fetching time is slow.

For this reason, as there is a div instruction previous to both BLT and MUL, I guess it's potentially a TRACER problem than a CPI problem.

Can you check if indeed the RTL waveforms of the CORE report what you see in the Tracer?

The mul instruction is implemented to take only 1 cycle, and the BLT takes 3 cycles in case it is taken (2 stalls) and 1 cycle if it is not taken.


Cheers,
Davide

**Comment by silabs-PaulZ** [comment]
Hi @barrydebruin , @davideschiavone , 

Here's a simulation of the above examples using the latest RTL. 
```
982.000 ns              324 0000bbda 02a64533 div              x10, x12, x10       x10=00000b6a x12:00680000 x10:0000091c
1051.000 ns             347 0000bbde 00ab8bb3 add              x23, x23, x10       x23=00000b6a x23:00000000 x10:00000b6a
1054.000 ns             **348 0000bbe2 f28b42e3 blt              x22, x8, -220       x22:00000000  x8:00000100
1066.000 ns             352 0000bb06 00098693 addi             x13, x19, 0         x13=00100f58 x19:00100f58
1069.000 ns             353 0000bb0a 00000713 addi             x14, x0, 0          x14=00000000
1072.000 ns             354 0000bb0e 00000c93 addi             x25, x0, 0          x25=00000000

```

And here as well...

```
664.000 ns             218 0000bafc 00f50533 add              x10, x10, x15       x10=02980000 x10:02340000 x15:00640000
667.000 ns             219 0000bb00 03454533 div              x10, x10, x20       x10=00530000 x10:02340000 x20:00000008
760.000 ns             ***250 0000bb04 02e70733 mul              x14, x14, x14       x14=00000000 x14:00000000 x14:00000000
763.000 ns             251 0000bb08 41275733 sra              x14, x14, x18       x14=00000000 x14:00000000 x18:00000004
766.000 ns             252 0000bb0c 40e50533 sub              x10, x10, x14       x10=00530000 x10:00530000 x14:00000000
769.000 ns             253 0000bb10 0b5000ef jal              x1, 2228             x1=0000bb14

```
The cycle count is behaving normally. The BLT is taking 4 cycles and MUL is 1 cycle. 
Can we go ahead and close this issue?

**Comment by Silabs-ArjanB** [comment]
We are closing this issue as it has been answered at least 7 days ago. Please do not hesitate to re-open this issue if you do not agree that the issue has been handled satisfactorily or if you have further questions.
