### ISSUE TITLE
Update marchid

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/cv32e40p#431]
marchid is currently implemented as a 'read 0' CSR, which is legal. 

It would be better to:

- [x] Use the value as defined for RI5CY at https://github.com/riscv/riscv-isa-manual/blob/master/marchid.md

- [x] Make a pull request at https://github.com/riscv/riscv-isa-manual/blob/master/marchid.md to change RI5CY into CV32E40P

**Comment by MikeOpenHWGroup** [comment]
This is being a little nit-picky, but I do not think the read value of zero is strictly illegal.  section 3.1.13 of the priviledged spec reads:
```
This register must be readable in any implementation, but a value of 0 can be returned to indicate the field is not implemented.
```
In the same sub-section it goes on to say,
```
Open-source project architecture IDs are allocated globally by the RISC-V Foundation
```
There does not seem to be a requirement that a given core should actually use this as its marchid.

Having sad that, I agree with @Silabs-ArjanB's suggestions and think we should do both.

**Comment by Silabs-ArjanB** [comment]
Agreed, as said above, the current implementation is legal as well.

**Comment by Silabs-ArjanB** [comment]
Sent email to the maintainer, kgf@iis.ee.ethz.ch, to make the following pull request:

-	Project name: CV32E40P
-	Maintainers: OpenHW
-	Point of contact: Davide Schiavone <davide@openhwgroup.org>
-	Architecture ID: 4
-	Project URL: https://github.com/openhwgroup/cv32e40p

**Comment by Silabs-ArjanB** [comment]
Changed into Doc issue as the RTL update has been performed already; now just awaiting the update of the documentation at https://github.com/riscv/riscv-isa-manual/blob/master/marchid.md

**Comment by davideschiavone** [comment]
A PR is pending here:

https://github.com/riscv/riscv-isa-manual/pull/578

**Comment by davideschiavone** [comment]
> 
> 
> A PR is pending here:
> 
> [riscv/riscv-isa-manual#578](https://github.com/riscv/riscv-isa-manual/pull/578)

The PR has been merged. We can close this issue
