### ISSUE TITLE
taken bge followed by div takes 36 cycles

### ISSUE THREAD

**Issue by GTumbush** [openhwgroup/cv32e40p#434]
**Component:RTL**: 

For specific combinations of bge followed by div the flush of the div takes 36 clock cycles. The branch is taken.
Other combinations of branch/div/mul/rem and operands may reproduce this issue.  I will enumerate a few below. 

### Steps to Reproduce
1. git hash: 2fe68a93c27db0bb514d567f79d3ba54045b51f6
2. git clone -b add_riscv_rand_instr_test_0 https://github.com/GTumbush/core-v-verif
3. cd cv32/sim/uvmt_cv32
4. make custom CUSTOM_PROG=riscv_branch_div

For:   
bge   a2, zero, fast_exit
div        a3, a6, a6
![image](https://user-images.githubusercontent.com/54555114/88854883-3fe9f280-d1af-11ea-8678-2fa0a1a0103e.png)

For:   
bge   a2, zero, fast_exit
div        a3, a6, **s1**
![image](https://user-images.githubusercontent.com/54555114/88855066-8e978c80-d1af-11ea-81cb-052820b679a8.png)

For:   
bge   a2, zero, fast_exit
**nop**
div        a3, a6, a6
![image](https://user-images.githubusercontent.com/54555114/88855317-e7672500-d1af-11ea-94ec-46dd3975ea70.png)

**Comment by GTumbush** [comment]
@MikeOpenHWGroup can you please assign this bug? I cannot.

**Comment by MikeOpenHWGroup** [comment]
Hi @davideschiavone.  Do you have time to look at this one?  It is urgent for em-micro.

**Comment by GTumbush** [comment]
Cloned Silabs-ArjanB:ArjanB_bge_div and verified as fixed.  
 
For:
bge a2, zero, fast_exit
div a3, a6, a6
![image](https://user-images.githubusercontent.com/54555114/91913242-5eda1980-ec72-11ea-8051-9516325f9979.png)

Other scenarios are similar.

**Comment by GTumbush** [comment]
Should not close until merged.

**Comment by GTumbush** [comment]
Fixed due to pull request https://github.com/openhwgroup/cv32e40p/pull/464 merged with master.
