### ISSUE TITLE
Illegal Instruction Exception Raised Incorrectly - C.EBREAK

### ISSUE THREAD

**Issue by shetalani** [openhwgroup/cv32e40p#439]
**RISC-V Specification:**

**Issue Description:**

Executing C.EBREAK instruction raises wrongly an illegal instruction exception. 

**Example:**

As shown below, the instruction 32'h00100073 (EBREAK) is decoded at time point t##0, where MSTATUS, MCAUSE and MEPC are updated at t##2 as if it had caused an illegal instruction exception.

![EBREAK_ill](https://user-images.githubusercontent.com/54367010/89549280-68ee3100-d808-11ea-8f4e-88648f556896.PNG)

**Top Level Parameters**
```
cv32e40p_core #(
    .FPU                      ( 0 ),
    .NUM_MHPMCOUNTERS         ( 1 ),
    .PULP_CLUSTER             ( 0 ),
    .PULP_XPULP               ( 0 ),
    .PULP_ZFINX               ( 0 )
) 
```
---
Product: OneSpin 360 DV-Verify
App: RVV
Tool's version: 2020.1.4

**Comment by Silabs-ArjanB** [comment]
Hi @shetalani , could you check if this issue has been fixed now on the not yet merged https://github.com/Silabs-ArjanB/cv32e40p/tree/ArjanB_illegal_instr_exc branch. If not, can you show a new violating waveform (and I will remove the resolved label again).

**Comment by Silabs-ArjanB** [comment]
![image](https://user-images.githubusercontent.com/40633348/91962861-65699f00-ed0d-11ea-80a2-5353b756495b.png)
