### ISSUE TITLE
Illegal Instruction Exception Raised Incorrectly - CSRs

### ISSUE THREAD

**Issue by shetalani** [openhwgroup/cv32e40p#440]
**RISC-V Specification:**

**Issue Description:**

Executing a CSR instruction raises wrongly an illegal instruction exception. 

**Example:**

As shown below, the instruction 32'h300035f3 (CSRRC X11, MSTATUS, X0) is decoded at time point t##0, where MSTATUS, MCAUSE and MEPC are updated at t##2 as if it had caused an illegal instruction exception.

![CSR_ill](https://user-images.githubusercontent.com/54367010/89549884-34c74000-d809-11ea-8a45-a3c43706a868.PNG)

**Top Level Parameters**
```
cv32e40p_core #(
    .FPU                      ( 0 ),
    .NUM_MHPMCOUNTERS         ( 1 ),
    .PULP_CLUSTER             ( 0 ),
    .PULP_XPULP               ( 0 ),
    .PULP_ZFINX               ( 0 )
) 
```
---
Product: OneSpin 360 DV-Verify
App: RVV
Tool's version: 2020.1.4

**Comment by Silabs-ArjanB** [comment]
Hi @shetalani , could you check if this issue has been fixed now on the not yet merged https://github.com/Silabs-ArjanB/cv32e40p/tree/ArjanB_illegal_instr_exc branch. If not, can you show a new violating waveform (and I will remove the resolved label again).

**Comment by Silabs-ArjanB** [comment]
![image](https://user-images.githubusercontent.com/40633348/91962947-803c1380-ed0d-11ea-8bc0-ac528775e51f.png)
