### ISSUE TITLE
Illegal Instruction Exception Raised Incorrectly - MRET

### ISSUE THREAD

**Issue by shetalani** [openhwgroup/cv32e40p#441]
**RISC-V Specification:**

**Issue Description:**

Executing MRET instruction raises wrongly an illegal instruction exception. 

**Example:**

As shown below, the instruction 32'h30200073 (MRET) is decoded at time point t##0, where MSTATUS, MCAUSE and MEPC are updated at t##2 as if it had caused an illegal instruction exception.

![MRET_ill](https://user-images.githubusercontent.com/54367010/89549734-fdf12a00-d808-11ea-8ea2-7fcb65506529.PNG)

**Top Level Parameters**
```
cv32e40p_core #(
    .FPU                      ( 0 ),
    .NUM_MHPMCOUNTERS         ( 1 ),
    .PULP_CLUSTER             ( 0 ),
    .PULP_XPULP               ( 0 ),
    .PULP_ZFINX               ( 0 )
) 
```
---
Product: OneSpin 360 DV-Verify
App: RVV
Tool's version: 2020.1.4

**Comment by Silabs-ArjanB** [comment]
Hi @shetalani , could you check if this issue has been fixed now on the not yet merged https://github.com/Silabs-ArjanB/cv32e40p/tree/ArjanB_illegal_instr_exc branch. If not, can you show a new violating waveform (and I will remove the resolved label again).

**Comment by Silabs-ArjanB** [comment]
![image](https://user-images.githubusercontent.com/40633348/91962980-8af6a880-ed0d-11ea-9d35-c01869cc43c6.png)
