### ISSUE TITLE
Illegal Instruction Exception Raised Incorrectly - FENCE

### ISSUE THREAD

**Issue by shetalani** [openhwgroup/cv32e40p#442]
**RISC-V Specification:**

**Issue Description:**

Executing FENCE instruction raises wrongly an illegal instruction exception. 

**Example:**

As shown below, the instruction 32'h7b21008f (FENCE) is decoded at time point t##0, where MSTATUS, MCAUSE and MEPC are updated at t##2 as if it had caused an illegal instruction exception.

![FENCE_ill](https://user-images.githubusercontent.com/54367010/89547367-f54b2480-d805-11ea-8771-f64f01aebf56.PNG)

**Top Level Parameters**
```
cv32e40p_core #(
    .FPU                      ( 0 ),
    .NUM_MHPMCOUNTERS         ( 1 ),
    .PULP_CLUSTER             ( 0 ),
    .PULP_XPULP               ( 0 ),
    .PULP_ZFINX               ( 0 )
) 
```
---
Product: OneSpin 360 DV-Verify
App: RVV
Tool's version: 2020.1.4

**Comment by Silabs-ArjanB** [comment]
Hi @shetalani , could you check if this issue has been fixed now on the not yet merged https://github.com/Silabs-ArjanB/cv32e40p/tree/ArjanB_illegal_instr_exc branch. If not, can you show a new violating waveform (and I will remove the resolved label again).

**Comment by Silabs-ArjanB** [comment]
![image](https://user-images.githubusercontent.com/40633348/91963002-92b64d00-ed0d-11ea-985f-3519b7e0ded2.png)
