### ISSUE TITLE
Incorrect DCSR value read/ written

### ISSUE THREAD

**Issue by shetalani** [openhwgroup/cv32e40p#443]
**RISC-V Specification:**

- **4.8.1** 

**Issue Description:**

Bits [27:16], [14] and [5] of DCSR should be tied to zero as specified in the spec. 

**Example:**

As shown below, the instruction 32'h7b0027f3 (CSRRSI X15, DCSR, X0) is decoded at time point t##0, where `dcsr_q.zero2` is read as 12'h800 at t##1. Same goes for `dcsr_q.zero1` or `dcsr_q.zero0`.

![DCSR_zero](https://user-images.githubusercontent.com/54367010/89544540-89b38800-d802-11ea-92a4-616f36294ece.PNG)

**Top Level Parameters**
```
cv32e40p_core #(
    .FPU                      ( 0 ),
    .NUM_MHPMCOUNTERS         ( 1 ),
    .PULP_CLUSTER             ( 0 ),
    .PULP_XPULP               ( 0 ),
    .PULP_ZFINX               ( 0 )
) 
```
---
Product: OneSpin 360 DV-Verify
App: RVV
Tool's version: 2020.1.4

**Comment by Silabs-ArjanB** [comment]
Hi @shetalani This issue should have been fixed now after the merge of https://github.com/openhwgroup/cv32e40p/pull/483 . Could you please check again and close this issue if fixed now?
