### ISSUE TITLE
mcounteren CSR should not exist

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/cv32e40p#448]
The official RISC-V spec was updated in response to https://github.com/riscv/riscv-isa-manual/issues/561, see https://github.com/riscv/riscv-isa-manual/commit/1eaebccc78d88f110a68faf1b39938fc291a4065 and comments on that commit).

We should remove mcounteren from CV32E40P (this issue relates to #432 as well, but the related questions have not been answered yet in the RISC-V organization).

**Comment by MikeOpenHWGroup** [comment]
I would be happy about this.  `mcounteren` is not currently modeled in the Reference Model and the CSR does nothing in the core (other than return 0).   Would removing this CSR mean that reads to 0x306 would invoke an illegal instruction exception?

**Comment by Silabs-ArjanB** [comment]
Yes that would be the consequence if we change this

**Comment by MikeOpenHWGroup** [comment]
Then I am in favor of this.
