### ISSUE TITLE
Custom linker script according to custom memory size

### ISSUE THREAD

**Issue by saumeister** [openhwgroup/cv32e40p#456]
Hi
Currently I'm trying to integrate the cv32e40p core to a 64kB instruction and data memory. But to generate the correct hex file for my memory size I need to customize linker script to place all data within the correct memory map. I use the linker script provided in the example_tb folder in this repository.

My inital try was change the MEMORY map to be within my memory size 0x65536
`ram (rwxai) : ORIGIN = 0x00000000, LENGTH = 0x64100 `
 `dbg (rwxai) : ORIGIN = 0x64200, LENGTH = 0x800`

However, when I look at the generated hex_file, some data sections are still placed outside my memory map address scope. Does anyone have some pointers to what I'm missing to change in the linker script?

Br
Saumeister

**Comment by MikeOpenHWGroup** [comment]
Hi @saumeister, thanks for the issue.  I would recommend that you close this issue and open an equivalent issue in the OpenHW [core-v-sw](https://github.com/openhwgroup/core-v-sw) repository.   This specific repo is for CV32E40P RTL issues, not software issues.
