### ISSUE TITLE
Instruction after stalled load retires out of order

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/cv32e40p#466]
In the following code (with the lw getting some wait states on rvalid), the later instruction (csr) retires before the earlier instruction (lw)

lw x5, 0(x4)      
csrw mepc, 0x1e

This at the very least leads to difficulties when doing state comparisons against an ISS (the shown example does not show an actual functional issue nor do I have a reason to think this is a functional issue).

![image](https://user-images.githubusercontent.com/40633348/91730879-9c717080-eba6-11ea-80e0-4de11e9c857d.png)

The same issue happens for a load followed by a regular ALU instruction:

lw x5, 0(x4)        
addi x21, x0, 0xff

![image](https://user-images.githubusercontent.com/40633348/91731634-5cf75400-eba7-11ea-841a-7127490e9173.png)

Maybe this issue is (partially) solved by https://github.com/openhwgroup/cv32e40p/pull/181 (I did not study that pull request).

**Comment by Silabs-ArjanB** [comment]
This is by design; it is not an RTL bug. Whether this is 'workable' for the verification team is up to them; if this retirement strategy leads to verification issues, then we can re-open this issue and consider whether we adapt the 'tracer' or the RTL. If the verification team only compares the 'destination register' against the ISS for each instruction (as opposed to the entire register file + CSR state), then the above effect should not be noticeable.

**Comment by davideschiavone** [comment]
The CSR instructions can be "fixed" by forcing the pipe to flush always, not only on special addresses of the csr.
The LW+ADD is by design yes. It's a WONT FIX because there is no real WB stage here...
