### ISSUE TITLE
cs_registers_i.a_single_step is not covered during Formal

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/cv32e40p#467]
The cover property of cs_registers_i.a_single_step is not reachable:

![image](https://user-images.githubusercontent.com/40633348/91755384-4d8a0200-ebcb-11ea-86cc-9cd90eb2852e.png)

**Comment by silabs-PaulZ** [comment]
I'm not seeing this issue on the master branch ( 4c27cf8  ) nor on my latest pull request to fix debug trigger bug #495

![image](https://user-images.githubusercontent.com/59703134/92776162-9cbafa00-f364-11ea-8bfa-136a6e94c470.png)

**Comment by Silabs-ArjanB** [comment]
Agreed; issue is no longer present
