### ISSUE TITLE
Debug Mode : ebreak instruction does not update dpc, dcsr before retire

### ISSUE THREAD

**Issue by eroom1966** [openhwgroup/cv32e40p#489]
when transitioning into Debug Mode, from Machine mode due to an ebreak instruction.
At the point where the ebreak is retured, the dpc and dcsr registers do not contain the correct value.
The values are correct 1 cycle after the instruction has retired.
This causes a miscompare as these registers are compared at the ebreak retire

(FYI)
@MikeOpenHWGroup 
@silabs-oysteink

**Comment by MikeOpenHWGroup** [comment]
Thanks for opening the issue @eroom1966.  Can you provide some specific steps to recreate this issue?  For example, the command-line for running the test that illustrates the error.

**Comment by Silabs-ArjanB** [comment]
Hi @eroom1966 Is the CV32E40P ever in an invalid state or is this purely about trying to align the ISS state with the RTL state (which could be potentially solved in the behavioral tracer or by ignoring the step-by-step comparison for a cycle)

**Comment by eroom1966** [comment]
@Silabs-ArjanB 
I think the internal state of the CV32E40P is correct.
I think the issue is only in the tracer/retire code which has indicated a retire one cycle too early, hence the state of dpc and dcsr is not correct for comparison purposes to the RM
The miscompare only exists for one instruction.

**Comment by Silabs-ArjanB** [comment]
Hi @eroom1966 Would you be okay with suppressing the check for 1 cycle (knowing that if there was an actual issue the following cycles would cause a mismatch as well)? I prefer not to change the RTL if not really needed.

**Comment by eroom1966** [comment]
@Silabs-ArjanB 
I would consider this a workaround rather than a solution - I would defer to @MikeOpenHWGroup to decide. Personally I would prefer the tracer to be fixed at source, workarounds are good, but tend to ignore the many potential side effects that may occur.

**Comment by MikeOpenHWGroup** [comment]
AFAIK, the tracer is not RTL, so I do not understand the concern about changing it.

**Comment by eroom1966** [comment]
@GTumbush @davideschiavone 
Hi Greg, Davide,
I wonder if you could help with the above, I note that @davideschiavone made changes to the retire behavior for the uret and mret instructions in order to ensure that the register state was correct at retirement.
It would appear that this is a similar issue with the ebreak instruction as described above the dpc and dcsr do not contain the correct values until a cycle later, so it would need changing thus

`if(~(trace.str == "mret" || trace.str == "uret")) begin`
to
`if(~(trace.str == "mret" || trace.str == "uret" || trace.str == "ebreak")) begin`

Does this look correct ?
Thx
Lee

**Comment by eroom1966** [comment]
addendum, to get this to work I had to do the following
if(~(trace.str == "mret" || trace.str == "uret" || trace.str == "ebreak" || trace.str == "c.ebreak")) begin

**Comment by GTumbush** [comment]
Hi Lee,
   Unfortunately, EM has not used the ISS in debug mode.  It seems the ISS is in a state in which we should.  I see no issues with your updates to the tracer but it would be best if someone from the design team blessed the change.

**Comment by Silabs-ArjanB** [comment]
Hi @eroom1966 This issue should be fixed now; can you close it if agreed? (core-v-verif will be made to point to the latest RTL)

**Comment by eroom1966** [comment]
agreed - closing
