### ISSUE TITLE
facing Error while installing RISC-V GNu toolchain

### ISSUE THREAD

**Issue by Prarthi1703** [openhwgroup/cv32e40p#530]
./configure --prefix=/opt/riscv
make linux

![gnu_toolchain_error](https://user-images.githubusercontent.com/70278960/94671074-03628080-0331-11eb-8caa-d36e7a8d7dbd.png)

**Comment by davideschiavone** [comment]
Hello, I think this is the wrong repository. You should open this ISSUE in the related github repository of your RISC-V GNU toolchain
