### ISSUE TITLE
Remove  apu_master_type_o, apu_master_ready_o pins and the master from the interface name

### ISSUE THREAD

**Issue by davideschiavone** [openhwgroup/cv32e40p#537]
To do after RTL freeze

**Comment by MikeOpenHWGroup** [comment]
How big of an impact would this be @davideschiavone?  Currently, neither the core or UVM testbenches drive/sink the APU interface, so the impact to verification would be hours, not days.

**Comment by davideschiavone** [comment]
Hi @MikeOpenHWGroup , yes but we did not want to change the core interface if not needed. Of course you drive the core verification effort, so if @Silabs-ArjanB agrees, I can remove these signals.

**Comment by Silabs-ArjanB** [comment]
Hi @davideschiavone I am okay with it if also https://github.com/openhwgroup/core-v-docs/issues/48 and the discussion in https://github.com/openhwgroup/cv32e40p/commit/61ef7f29948959e94331aabb02591a98de4a80b5#commitcomment-42890979 get resolved.

**Comment by davideschiavone** [comment]
A PR related to the RTL is here #558 
Whereas the one related to documentation is here: https://github.com/openhwgroup/core-v-docs/pull/233

**Comment by davideschiavone** [comment]
#558 has been merged. Closing this issue
