### ISSUE TITLE
HWLoop minimum size 3 illegal exception

### ISSUE THREAD

**Issue by davideschiavone** [openhwgroup/cv32e40p#583]
As the HWloop body must be at least 3 instructions, the core should raise an illegal exception when this is not respected

In addition, as the lp.starti and lp.endi instruction use the immediate by aligned implicitly (<<1) as specified here

https://core-v-docs-verif-strat.readthedocs.io/projects/cv32e40p_um/en/latest/instruction_set_extensions.html#operations

we should change their definition by forcing word alignment (<<2) as it is a constraint of the HWloop

https://core-v-docs-verif-strat.readthedocs.io/projects/cv32e40p_um/en/latest/pulp_hw_loop.html

Pinging @jeremybennett , @jm4rtin  and @eflamand

**Comment by davideschiavone** [comment]
Before proceeding and updating the documentation , we want to try the RTL (by means of hexadecimal instructions) to avoid that the SW team modifies the custom HWLoop relocation before RTL gets tested as agreed with @jm4rtin and @jeremybennett

**Comment by davideschiavone** [comment]
@pascalgouedo - we agreed that the Core won't trap to any exception - shall I close it?

**Comment by pascalgouedo** [comment]
Hi @davideschiavone 
Yes both updates (no trap and shift by 2) have been included in v1.2.0 User Manual.
