### ISSUE TITLE
Move Documenation to this repository

### ISSUE THREAD

**Issue by davideschiavone** [openhwgroup/cv32e40p#613]
The current documentation is located at https://github.com/openhwgroup/core-v-docs

We want to move the folder here and all the relateve issues

**Comment by Silabs-ArjanB** [comment]
Hi @davideschiavone We already did this change for the 40X/40S. When you do it for the 40P can you follow the following directory structure?

cv32e40p/docs/user_manual/images
cv32e40p/docs/user_manual/make.bat
cv32e40p/docs/user_manual/Makefile
cv32e40p/docs/user_manual/source
