### ISSUE TITLE
Pinout: Document Auxiliary Processing Unit (APU) interface

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/cv32e40p#615]
Currently there is no documentation about this interface in the User Manual. I added the core-v-docs/cores/cv32e40p/user_manual/source/apu.rst file to start the documentation for this feature including a list of the associated pins (and will do a pull request for this soon). 

We need to have (at least) the following information in this section:

- Description of the mentioned signals
- Protocol (and semantics) of the mentioned signals
- High level purpose of this interface
- Clarification of the WAPUTYPE value (it is currently 0 leading to apu_master_type_o[-1:0] (negative range)
- Interaction with the FPU
- Relationship with the FPU parameter (if any)
- Relationship with the PULP_ZFINX parameter (if any)

**Comment by pascalgouedo** [comment]
APU interface is not visible anymore in new CV32E40P top level (cv32e40p_top). Only used internally to connect FPU.
