### ISSUE TITLE
A test bench to demonstrate the register+clock network power of RI5CY Core

### ISSUE THREAD

**Issue by ranaya123** [openhwgroup/cv32e40p#631]
Hello,

I have been doing experiments with former RI5CY core from Pulpissimo platform and since this is the replacement core for that, I'll post my question here.

I want to compare the integration of a novel flip flop to a standard single-edge triggering flop-flop using the same core. What is the best suited test bench application, in this case, to demonstrate the effective clock network/register power savings ? Or could you please suggest an application for that ? i.e. I ran coremark and it shows savings only upto ~20%

Thanks in advance
Anuradha

**Comment by Silabs-ArjanB** [comment]
Hi @ranaya123 Power consumption is of course very application specific and as such it is difficult to recommend a good benchmark. I believe it is fair to use Coremark (as at least many people use it). You could also report your numbers for a bit more modern benchmark as for example Embench (https://www.embench.org/, https://github.com/embench/embench-iot) although they don't have standardized power metrics yet. SPEC you could use as well.
