### ISSUE TITLE
Does this core support atomic instruction set

### ISSUE THREAD

**Issue by AkhilBR98** [openhwgroup/cv32e40p#654]

**Comment by MikeOpenHWGroup** [comment]
Hi @AkhilBR98, thanks for your interest.  The short answer to your question is "no".  The CV32E40P is an RV32IMCZ core (Z extensions are Zicount, Zicsr amd Zifencei).  The complete User Manual for this core is [here](https://cv32e40p.readthedocs.io/en/latest/intro/).   The CV32E40P can optionally support floating point and some custom instructions, but these are not yet fully verified.

The [CV32E40X](https://docs.openhwgroup.org/projects/cv32e40x-user-manual/index.html) (still in development) supports atomic instructions.
