### ISSUE TITLE
misa CSR is documented as read/write - should be read-only

### ISSUE THREAD

**Issue by jeremybennett** [openhwgroup/cv32e40p#655]
https://cv32e40p.readthedocs.io/en/latest/control_status_registers/#cs-registers lists `misa` as `MRW`, it should be `MRO`

### Type
Indicate whether the type of problem you found:
* Factually incorrect information.

### Location of Issue
Please provide:
1. URL to the document: https://cv32e40p.readthedocs.io/en/latest/control_status_registers/#cs-registers

### Additional context
None

**Comment by davideschiavone** [comment]
this issue belongs to cv32e40p
