### ISSUE TITLE
cv.add.{div2,div4,div8} encoding in DOC does not match RTL

### ISSUE THREAD

**Issue by davideschiavone** [openhwgroup/cv32e40p#657]
In the documentation, 

cv.add.{div2,div4,div8} func5 (bits 31-27) are: **01011**

However, the RTL is: **01110**

This is an error of the Documentation that may effect the compiler too

**Comment by davideschiavone** [comment]
@nbruschi, can you comment about the compiler? what does it implement?

**Comment by NBruschi** [comment]
If I'm not mistaken, SIMD instructions were not already in development at the toolchain side. Am I right @jeremybennett ?

**Comment by davideschiavone** [comment]
asking also @jessicamills

**Comment by jessicamills** [comment]
@davideschiavone, @NBruschi is correct. We have not added SIMD instructions to the tool chain.
