### ISSUE TITLE
Linux Compatible

### ISSUE THREAD

**Issue by SOUMYADIPSAHA10** [openhwgroup/cv32e40p#671]
Hello,
Is this Core Linux compatible?

**Comment by MikeOpenHWGroup** [comment]
The CV32E40P is a "embedded class" processor intended to be used in IoT devices.  If you are looking for an "application class" processor have a look at the [CVA6](https://github.com/openhwgroup/cva6).  That core has a configurable XLEN (32- and 64-bit) and runs Linux in both configurations.
