### ISSUE TITLE
Immediate scalar replication mode example 

### ISSUE THREAD

**Issue by a7med7asan15** [openhwgroup/cv32e40p#710]
Hi OpenHw Team, 
In Immediate scalar replication mode section. It is described here: 

> Immediate scalar replication mode (.sci), vector-scalar operation. Operand 1 is treated as vector, while operand 2 is treated as a scalar and comes from an immediate. The immediate is either sign- or zero-extended, depending on the operation. If not specified, the immediate is sign-extended.
e.g. cv.add.sci.h x3,x2,0xDA performs:
x3[31:16] = x2[31:16] + 0xFFDA
x3[15: 0] = x2[15: 0] + 0xFFDA

The immediate is only 6 bits wide, Shouldn't the maximum value for the immediate to be 0x3F (0011 1111) ? Why the example mentioned 0xDA (1101 1010) ? 

Also in the decoding tables, Sometimes the immediate is Imm6[5:0]s or Imm6[5:0], What is the difference between both? With and without the letter s 

Thanks

**Comment by MikeOpenHWGroup** [comment]
Hi @a7med7asan15, I am not clear about why you closed this issue.  Is your question answered?  If so, where?
