### ISSUE TITLE
How to build C standard lib to RV32I instead of RV32IMC?

### ISSUE THREAD

**Issue by neekoli** [openhwgroup/cv32e40p#711]
Recently, I need to build my program into **RV32I**（every instruction）. But it seems that C standard lib **(e.g stdio.h string.h stdint...)** would be built into **RV32IMC** . I feel really puzzled and find nowhere to configurate the build options.

**Comment by MikeOpenHWGroup** [comment]
Hi @neekoli.  This is a toolchain issue, not an issue related to the cv32e40p.
