### ISSUE TITLE
FMUL.S instructions set underflow flag of fflags wrongly

### ISSUE THREAD

**Issue by salaheddinhetalani** [openhwgroup/cv32e40p#729]
### Issue Description
FMUL.S instructions set underflow flag "UF" of fflags wrongly. 

### Component
**Component:RTL**

### RISC-V Specification
> The Zfinx extension adds all of the instructions that the F extension adds, except for the transfer instructions FLW, FSW, FMV.W.X, FMV.X.W, C.FLW[SP], and C.FSW[SP].

>The Zfinx variants of these F-extension instructions have the same semantics, except that whenever such an instruction would have accessed an f register, it instead accesses the x register with the same number.

### Steps to Reproduce

As shown below, the following sequence of instructions happens: 
> fmul.s x15, x12, x8, RUP

The instruction `fmul.s` is decoded at `t##0` and executed updating the integer register file at `t##1` while setting the underflow flag `UF` of `fflags` CSR wrongly. 

![Bug_12](https://user-images.githubusercontent.com/28307467/192500803-34a524b4-ab7e-4eba-8304-9725d7b52d3a.png)

**Top Level Parameters**
```
cv32e40p_wrapper #(
    .PULP_XPULP       (0),
    .PULP_CLUSTER     (0),
    .FPU              (1),
    .PULP_ZFINX       (1),
    .NUM_MHPMCOUNTERS (1)
)
```
Git Hash: https://github.com/openhwgroup/cv32e40p/commit/d0d1c25374e3770c4335568ef16e84404cedbdea
Flist: [cv32e40p_fpu_manifest.flist](https://github.com/openhwgroup/cv32e40p/blob/master/cv32e40p_fpu_manifest.flist.) 
VCD: [bug_12.vcd](https://github.com/openhwgroup/cv32e40p/files/9657034/bug_12.zip)

---
Product: OneSpin 360 DV-Verify
App: Processor Verification App
Tool's version: 2022.3_1

**Comment by pascalgouedo** [comment]
Resolved with PR #860
