### ISSUE TITLE
Non-existent Zicount extension mentioned in introduction

### ISSUE THREAD

**Issue by jstraus59** [openhwgroup/cv32e40p#767]
The CV32E40P documentation mentions a "Zicount" instruction set extension that does not appear to exist.

**Comment by Silabs-ArjanB** [comment]
Zicount was the assumed name when RISC-V had not yet standardized a name for it. The correct names will be Zicntr and Zihpm. See 'Counters' chapter of the most recent RISC-V Unprivileged specification.

**Comment by pascalgouedo** [comment]
Thanks @jstraus59 and @Silabs-ArjanB 
I am updating the User Manual for that point.

**Comment by davideschiavone** [comment]
> Thanks @jstraus59 and @Silabs-ArjanB I am updating the User Manual for that point.

thanks a lot @pascalgouedo

**Comment by pascalgouedo** [comment]
Corrected by PR #775 and available with 1.3.0 User Manual.
