### ISSUE TITLE
PULP_ZFINX implementation details

### ISSUE THREAD

**Issue by jstraus59** [openhwgroup/cv32e40p#768]
The documentation for CV32E40P defines the PULP_ZFINX configuration option but provides no implementation details.

I assume that enabling this option implements the RiscV Standard Zfinx extension. If so, this should be explicitly stated in the documentation and a reference document specified, including the version of the specification that is implemented.

**Comment by pascalgouedo** [comment]
Hi @jstraus59 
Yes I agree. v1.2.1 is not the final spec and it contains only re-encoding and hardware loops clarification.
There are still clean-up and clarifications (a lot) to be done and PULP_ZFINX to Zfinx v1.0 switch is one of them.
