### ISSUE TITLE
Minor error in specification of `cv.insert` and `cv.insertr` instructions

### ISSUE THREAD

**Issue by jstraus59** [openhwgroup/cv32e40p#769]
## Minor error in specification of `cv.insert` and `cv.insertr` instructions
The description for the `cv.insert` and `cv.insertr` instructions in the Bit Manipulation Operations table of the documentation states:

> Is3 + Is2 must be <= 32

I believe that since Is3 contains the length of the field **minus 1**, this should be:

> Is3 + Is2 must be < 32

### Component
**Component:Doc**

**Comment by pascalgouedo** [comment]
Corrected by PR #775 and available with 1.3.0 User Manual.
