### ISSUE TITLE
Possible Improvement on Naming of "rd" in Hardware Loop Extension

### ISSUE THREAD

**Issue by realqhc** [openhwgroup/cv32e40p#770]
Hardware Loops now uses "rd" to name its 11:08 field, which is not actually a register field, but a function field used to specify which function is used. It could be better named to "funct4" or other funct related name, so that misunderstanding could be avoided.

**Comment by pascalgouedo** [comment]
Hi @realqhc 
I agree, it is named like that in the summarizing excel sheet.
I will update the User Manual.

**Comment by pascalgouedo** [comment]
Corrected by PR #775 and available with 1.3.0 User Manual.
