### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by cybird1996** [openhwgroup/cv32e40p#773]
What are the steps to implement this core on zedboard fpga

**Comment by MikeOpenHWGroup** [comment]
Hi @cybird1996, thanks for your interest in the CV32E40P.  Your question is very open ended and we do not offer design consulting services.  A good place for you to start might be the [CORE-V-MCU](https://github.com/openhwgroup/core-v-mcu), and in particular its [Quick Start Guide](https://github.com/openhwgroup/core-v-mcu/blob/master/emulation/quickstart/README.md).

Closing the issue.
