### ISSUE TITLE
Did Post-Incrementing Load & Store Instructions and Register-Register Load & Store Instructions support misalign load or store

### ISSUE THREAD

**Issue by fanghuaqi** [openhwgroup/cv32e40p#789]
Hello,

In this page https://docs.openhwgroup.org/projects/cv32e40p-user-manual/en/latest/instruction_set_extensions.html#post-incrementing-load-store-instructions-and-register-register-load-store-instructions, these instructions are used to save instructions of load/store, but it didn't mention that whether it support mis-aligned load or store? 

Could someone give some hints about it.

Thanks

**Comment by pascalgouedo** [comment]
Hi,

As mentioned in [Load-Store-Unit chapter](https://docs.openhwgroup.org/projects/cv32e40p-user-manual/en/latest/load_store_unit.html#misaligned-accesses), misaligned accesses are fully supported.

New custom Load/Store are no exception to that.

Regards.
