### ISSUE TITLE
Is there any physical synthesis performed using 5nm technology for cv32e40p ? 

### ISSUE THREAD

**Issue by hansaniesamarasinghe** [openhwgroup/cv32e40p#798]
If there is anyone who has done physical synthesis for cv32e40p processor using 5nm technology, can you please share PPA values just to compare? If there's any published paper or article would also be nice

**Comment by MikeOpenHWGroup** [comment]
Thanks for your interest in the CV32E40P @hansaniesamarasinghe.  The information you are looking for would be considered proprietary to the owners of the PDK and probably the synthesis tools as well, so we do not publish such results.

**Comment by pascalgouedo** [comment]
We don't have those informations.
So I close the issue.
