### ISSUE TITLE
Link to readthedocs on landing page no longer works

### ISSUE THREAD

**Issue by jstraus59** [openhwgroup/cv32e40p#839]
As of today the [link to the documentation on the landing page](https://docs.openhwgroup.org/projects/cv32e40p-user-manual/en/latest) has stopped working.

This is what I get when I select it: 
![image](https://github.com/openhwgroup/cv32e40p/assets/10142791/b658e158-a360-4729-9195-a8f9d9333ba2)

It was working yesterday. Looks like something changed at readthedocs?

**Comment by jstraus59** [comment]
FYI, using google I did find this alternative URL that does work:
https://openhw-group-cv32e40p-user-manual.readthedocs-hosted.com/en/cv32e40p_v1.3.2

**Comment by MikeOpenHWGroup** [comment]
Hi Jim.  This is a fat-finger problem at our end.  It is being actively worked on.  In the meantime, for the E40P, the following link works: https://cv32e40p.readthedocs.io/en/latest/index.html.

**Comment by jstraus59** [comment]
Thanks Mike. Closing issue.
