### ISSUE TITLE
data forward violation when custom xpulp instruction, cv.insertr followed by fp instructions

### ISSUE THREAD

**Issue by dd-baoshan** [openhwgroup/cv32e40p#870]
Simulation shows below Imperas error messages which related to bsetr xpulp instruction.

![image](https://github.com/openhwgroup/cv32e40p/assets/131629054/7b7895cd-9a9a-4e6d-ade9-eee26a57032a)

From tracer log, we can see that the data forward rule is violated whereby the fmul.s rd is not reflecting correctly on cv.insertr r2

![image](https://github.com/openhwgroup/cv32e40p/assets/131629054/cf1dc090-30ca-4d6f-b341-7fa729ec1425)

It was proven in waves whereby we can see that cv.insertr write to register earlier than its preceded fmul instruction (blue marker indicate fmul reg_write to X10 happen after cv.insertr reg_write to X20 )

![image](https://github.com/openhwgroup/cv32e40p/assets/131629054/a7e50e61-0b42-4065-8e1a-b3c82ac86f2a)

Further debug shows that the apu_stall signal is not asserted when cv.insertr has dependency on X10 (the read_reg_valid_i[1] deasserted during cv.insertr decoding stage). 
-	cv.insertr has alu_op_b_mux_sel_o set to OP_B_MASK in decoder_i

![image](https://github.com/openhwgroup/cv32e40p/assets/131629054/03dcf219-d7aa-4210-95cb-d2d56d6d633e)

-	but dependency check for op_b has no include OP_B_MASK as option thus de-assert the apu_read_reg_valid[1]

![image](https://github.com/openhwgroup/cv32e40p/assets/131629054/f2d21b6f-4b82-48a2-9845-30a4e8deb8c0)

Component:RTL

### Steps to Reproduce
Please provide:
1. cv32e40p git hash : https://github.com/openhwgroup/cv32e40p/commit/4d281cf231fa2b5b7f2b600dd8b399a248c1f279
2. Users need to checkout below core-v-verif to replicate the issue. The reproduce steps as followings
git clone --branch cv32e40p/bsm-github_cv32e40p_Issue_0907 https://github.com/XavierAubert/core-v-verif.git sandbox
cd sandbox/cv32e40p/sim/uvmt
make gen_corev-dv TEST=corev_rand_fp_instr_data_fwd_test CFG=pulp_fpu_zfinx_2cyclat SIMULATOR=vsim SEED=1406786435 TEST_CFG_FILE=floating_pt_zfinx_instr_en COREV=1 USE_ISS=YES
make test TEST=corev_rand_fp_instr_data_fwd_test CFG=pulp_fpu_zfinx_2cyclat SIMULATOR=vsim SEED=1406786435 TEST_CFG_FILE=floating_pt_zfinx_instr_en USE_ISS=YES

**Comment by pascalgouedo** [comment]
Resolved with PR #881
