### ISSUE TITLE
data forward violation when custom xpulp instruction, cv.bclrr followed by fp instructions

### ISSUE THREAD

**Issue by dd-baoshan** [openhwgroup/cv32e40p#876]
Issue similar to data forward violation when custom xpulp instruction, cv.bsetr followed by fp instructions · Issue #869 

Information as following
Simulation shows below Imperas error messages which related to bclrr xpulp instruction.

![image](https://github.com/openhwgroup/cv32e40p/assets/131629054/d07df2bf-2b6d-4ac2-8885-cdf52b61b587)

From tracer log, we can see that the data forward rule is violated whereby the fmin rd is not reflecting correctly on cv.bclrr rs2

![image](https://github.com/openhwgroup/cv32e40p/assets/131629054/da85d78c-af6e-4a30-9347-9e1ad79a9ef0)

Component:RTL

Steps to Reproduce

1) cv32e40p git hash :  7e131050c88bd57b2866887eea7de07735f60706
2) Users need to checkout below core-v-verif to replicate the issue. The reproduce steps as followings.

2.1) git clone --branch  cv32e40p/bsm-github_cv32e40p_Issue_0912  https://github.com/XavierAubert/core-v-verif.git sandbox
2.2) cd sandbox/cv32e40p/sim/uvmt
2.3)make gen_corev-dv TEST=corev_rand_fp_instr_data_fwd_test CFG=pulp_fpu_zfinx_2cyclat SIMULATOR=vsim SEED=1046126087 TEST_CFG_FILE=floating_pt_instr_zfinx_en COREV=1 USE_ISS=YES
2.4) make test  TEST=corev_rand_fp_instr_data_fwd_test CFG=pulp_fpu_zfinx_2cyclat SIMULATOR=vsim SEED=1046126087 TEST_CFG_FILE=floating_pt_instr_zfinx_en USE_ISS=YES

**Comment by pascalgouedo** [comment]
Resolved with PR #881
