### ISSUE TITLE
data forward violation when custom xpulp instructions, cv.extractr / cv.extractur followed by fp instructions

### ISSUE THREAD

**Issue by dd-baoshan** [openhwgroup/cv32e40p#877]
Issue related to data forward violation when custom xpulp instruction followed by fp instructions.

Information as following:
Simulation shows below Imperas error messages which related to cv.extractr xpulp instruction.

![image](https://github.com/openhwgroup/cv32e40p/assets/131629054/c7dfdab5-8ada-461a-8a2d-11d8b3819606)

From tracer log, we can see that the data forward rule is violated whereby the fmin rd is not reflecting correctly on cv.bclrr rs2

![image](https://github.com/openhwgroup/cv32e40p/assets/131629054/1006f3a4-ad88-40f2-b5e2-cdae7613bf09)

![image](https://github.com/openhwgroup/cv32e40p/assets/131629054/b79eeade-e8bf-48c6-b9aa-28ec442b4c09)

Component:RTL

Steps to Reproduce
1) cv32e40p git hash:     7e131050c88bd57b2866887eea7de07735f60706
2)  core-v-verif git hash: f0c10adf74d43ffc8896960cdad5c3b32956cb81
3) Users need to checkout below core-v-verif to replicate the issue. The reproduce steps as followings.

3.1) git clone --branch  cv32e40p/dev_dd  https://github.com/XavierAubert/core-v-verif.git sandbox
cd sandbox/cv32e40p/sim/uvmt
3.2) make gen_corev-dv TEST=corev_rand_fp_instr_data_fwd_test CFG=pulp_fpu_zfinx_2cyclat SIMULATOR=vsim SEED=819516268 TEST_CFG_FILE=floating_pt_instr_zfinx_en COREV=1 USE_ISS=YES
3.3) make test  TEST=corev_rand_fp_instr_data_fwd_test CFG=pulp_fpu_zfinx_2cyclat SIMULATOR=vsim SEED=819516268 TEST_CFG_FILE=floating_pt_instr_zfinx_en USE_ISS=YES

**Comment by pascalgouedo** [comment]
Resolved with PR #881
