### ISSUE TITLE
Suggested update to the FPGA Synthesis sub-section of the User Manual

### ISSUE THREAD

**Issue by MikeOpenHWGroup** [openhwgroup/cv32e40p#948]
The User Manual has a short [FPGA Synthesis](https://github.com/openhwgroup/cv32e40p/blob/master/docs/source/integration.rst#fpga-synthesis) sub-section.  Based on recent discussions (see #943), we should consider updating this text:

1. The sentence `FPGA synthesis is only supported for CV32E40P` is confusing.  Maybe the word "_only_" is not intended to be there?
2. We could list the FPGA synthesis tools that have been successfully used for this core.
3. Mention that `Quartus Prime Standard` is not supported (`Quartus Prime Pro` is required).

**Comment by pascalgouedo** [comment]
Corrected in PR #956.
