### ISSUE TITLE
Clarification on cv.clipr signedness

### ISSUE THREAD

**Issue by realqhc** [openhwgroup/cv32e40p#967]
> That is a fair point. I raised this issue with the hw group and we should have soon an update that clarifies this. I think that having bit 31 zero (so rs2 being positive) is a requirement for correctness of the operation. In that case we'd need a check on the operand value. I agree with separating this patch into two for now: intrinsics support and codegen.

_Originally posted by @PaoloS02 in https://github.com/llvm/llvm-project/pull/78138#discussion_r1524938040_

Does cv.clipr require bit 31 being zero to function correctly? or it automatically treats the bit 31 as zero even if it is 1 (e.g. it performs abs before actual operation)?

**Comment by pascalgouedo** [comment]
I am working on it since last week.
Same pb than https://github.com/openhwgroup/cv32e40p/commit/1a58c7b7666ac693d936c45b4ed9dc0d762e1bf6#commitcomment-138230716

**Comment by pascalgouedo** [comment]
Corrected with PR #971
