### ISSUE TITLE
Floating Point Unit (FPU) not working

### ISSUE THREAD

**Issue by 10xloop** [openhwgroup/cv32e40p#990]
I am unable to run the "FADD" test for the CV32E40P Core. Initially, a few definitions were missing in the include package, such as the code for different types of exceptions. After adding those definitions, it compiles perfectly, but when I try to run it with "Verilator," it gets stuck in "dumping memory ..........

![dump_memory](https://github.com/openhwgroup/cv32e40p/assets/127600212/ec5f6a50-6a81-445c-bfb7-a2f3db5f5d51)

**Comment by MikeOpenHWGroup** [comment]
Hi @10xloop thanks for you Issue.  It appears that you are using the "core" testbench.  Please be aware that this testbench is only a demonstration platform.  We do not use it for verification of our cores and it is not expected to support all test-programs.  (As far as I know, it cannot support any floating point instructions at this time.)

If you are interested in adding this support for the core testbench, please reach out to me at mike@openhwhgroup.org and we can discuss it.
