### ISSUE TITLE
Debug: Which version of OpenOCD

### ISSUE THREAD

**Issue by CLappin** [openhwgroup/cv32e40p#999]
Hi all, 

Which version of openocd should be used with the [pulp debugger](https://github.com/pulp-platform/riscv-dbg).

I've tried the latest version which doesn't connect correctly, I've also tried the 0.10.0 version that I had which seemed to all connection via telnet. 

Any help would be great , 
Thanks,
Ciaran

**Comment by pascalgouedo** [comment]
There is no debug unit neither in cv32e40p system nor in core-v-verif test-bench.

Better to ask in https://github.com/pulp-platform/riscv-dbg/issues or to the 2 projects mentioned by Mike.

**Comment by CLappin** [comment]
Thanks @MikeOpenHWGroup  and @pascalgouedo , I'll check those other groups now.
